version: "3.3"
services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE=db_proyecto_www
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/app/
    command: npm run dev && npm install
    depends_on:
      - db
    
